version: 2
updates:
  # Ruby dependencies
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "ruby"
    assignees:
      - "NaaaRiii"
    open-pull-requests-limit: 5
    groups:
      rails:
        patterns:
          - "rails*"
          - "actioncable"
          - "actionmailer"
          - "actionpack"
          - "actiontext"
          - "actionview"
          - "activejob"
          - "activemodel"
          - "activerecord"
          - "activestorage"
          - "activesupport"
          - "railties"
      
  # JavaScript dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "javascript"
    assignees:
      - "NaaaRiii"
    open-pull-requests-limit: 5
    groups:
      vite:
        patterns:
          - "vite*"
          - "@vitejs/*"
      testing:
        patterns:
          - "vitest*"
          - "@vitest/*"
      linting:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier*"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "NaaaRiii"