plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'app/services/analysis_storage_service.rb'


Metrics/ClassLength:
  Max: 400
  Exclude:
    - 'app/services/sentiment_analyzer.rb'

RSpec/MultipleExpectations:
  Max: 5

RSpec/DescribeClass:
  Exclude:
    - 'spec/lib/sample_unit_spec.rb'
    - 'spec/models/sample_spec.rb'

RSpec/MultipleMemoizedHelpers:
  Max: 6

RSpec/NestedGroups:
  Max: 4

Rails/SkipsModelValidations:
  Exclude:
    - 'app/services/message_batch_service.rb'
    - 'app/models/concerns/cacheable_message.rb'

Naming/PredicateMethod:
  Exclude:
    - 'app/services/message_batch_service.rb'
    - 'app/controllers/application_controller.rb'

Metrics/AbcSize:
  Max: 35
  Exclude:
    - 'app/services/message_batch_service.rb'
    - 'app/services/analysis_storage_service.rb'

RSpec/ExampleLength:
  Max: 20

RSpec/AnyInstance:
  Enabled: false

RSpec/LetSetup:
  Exclude:
    - 'spec/system/**/*'

RSpec/IndexedLet:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/system/**/*'

inherit_from:
  - rubocop/security.yml
  - rubocop/project_policies.yml
  - .rubocop_todo.yml